{"name": "[Negative] Verify user can't login using wrong password", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'", "trace": "set_up = <generator object set_up at 0x0000025D49DF6190>\n\n    @step(\"user try login with incorrect password\")\n    @story(\"User will failed login to website if credentials are incorrect\")\n    @title(\"[Negative] Verify user can't login using wrong password\")\n    def test_login_incorrect_password(set_up):\n        driver = set_up\n        login_page = Login_page(driver)\n    \n        # Perform login with incorrect credentials\n>       login_page.login_as(\"standard_user\", \"secret_sauc\")\n\ntests\\test_login.py:45: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage\\login_page.py:50: in login_as\n    self.insert_credentials(username, password)\npage\\login_page.py:45: in insert_credentials\n    self.insert_username(username)\npage\\login_page.py:25: in insert_username\n    self.action.double_click(self.get(self.username_col))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page.login_page.Login_page object at 0x0000025D49E4AA20>, identfier = ('id', 'user-name')\n\n    def get(self, identfier:tuple) -> object:\n        \"\"\"Get element object by identifier\n    \n        Args:\n            identfier (tuple): For example, (By.ID, \"user-name\") or else.\n    \n        Returns:\n            object: Element object\n        \"\"\"\n>       return self.driver.find_element(*identfier)\nE       AttributeError: 'generator' object has no attribute 'find_element'\n\npage\\POM.py:77: AttributeError"}, "steps": [{"name": "user try login with incorrect password", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'\n", "trace": "  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\tests\\test_login.py\", line 45, in test_login_incorrect_password\n    login_page.login_as(\"standard_user\", \"secret_sauc\")\n  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 50, in login_as\n    self.insert_credentials(username, password)\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 45, in insert_credentials\n    self.insert_username(username)\n  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 25, in insert_username\n    self.action.double_click(self.get(self.username_col))\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\POM.py\", line 77, in get\n    return self.driver.find_element(*identfier)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Login as 'standard_user' with password ''secret_sauc''", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'\n", "trace": "  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 50, in login_as\n    self.insert_credentials(username, password)\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 45, in insert_credentials\n    self.insert_username(username)\n  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 25, in insert_username\n    self.action.double_click(self.get(self.username_col))\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\POM.py\", line 77, in get\n    return self.driver.find_element(*identfier)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Insert username as 'standard_user'", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'\n", "trace": "  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 25, in insert_username\n    self.action.double_click(self.get(self.username_col))\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\POM.py\", line 77, in get\n    return self.driver.find_element(*identfier)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "username", "value": "'standard_user'"}], "start": 1740992133933, "stop": 1740992133933}], "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'secret_sauc'"}], "start": 1740992133933, "stop": 1740992133935}], "parameters": [{"name": "set_up", "value": "<generator object set_up at 0x0000025D49DF6190>"}], "start": 1740992133933, "stop": 1740992133936}], "start": 1740992133933, "stop": 1740992133937, "uuid": "9add9213-47ba-4f38-b035-d381d5144135", "historyId": "ad387778e25dc5b6051a2dfd42784c1f", "testCaseId": "ad387778e25dc5b6051a2dfd42784c1f", "fullName": "tests.test_login#test_login_incorrect_password", "labels": [{"name": "feature", "value": "Login"}, {"name": "severity", "value": "blocker"}, {"name": "suite", "value": "Validate Login Functionality"}, {"name": "story", "value": "User will failed login to website if credentials are incorrect"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "LOQ15"}, {"name": "thread", "value": "11892-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}