[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E3EF48D790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6d4712d9b93650a348f392c1f63f0e6f/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E3EF48E330>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6d4712d9b93650a348f392c1f63f0e6f/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E3EF48CD70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6d4712d9b93650a348f392c1f63f0e6f/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E3EF48D040>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6d4712d9b93650a348f392c1f63f0e6f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E3EF48FFB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6d4712d9b93650a348f392c1f63f0e6f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E3EF48F530>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6d4712d9b93650a348f392c1f63f0e6f